// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVsZipmMbdsZqU6_xwKawdX3bykTyPV-o',
    appId: '1:992893123986:web:ab48df0e81046eeae7954b',
    messagingSenderId: '992893123986',
    projectId: 'whats-app-713e4',
    authDomain: 'whats-app-713e4.firebaseapp.com',
    storageBucket: 'whats-app-713e4.appspot.com',
    measurementId: 'G-1SGPWPT2HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmyJFG0AJ29GnsqaefRiA0r2OZdXwun6o',
    appId: '1:992893123986:android:47487f2bdb43f521e7954b',
    messagingSenderId: '992893123986',
    projectId: 'whats-app-713e4',
    storageBucket: 'whats-app-713e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS5NYarP3oWDw9d2D2V2NoI531Qs7nI2o',
    appId: '1:992893123986:ios:f005b75f92830e11e7954b',
    messagingSenderId: '992893123986',
    projectId: 'whats-app-713e4',
    storageBucket: 'whats-app-713e4.appspot.com',
    iosClientId: '992893123986-uudjlfl2glvvvfs4oapktc0ne8tbv438.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS5NYarP3oWDw9d2D2V2NoI531Qs7nI2o',
    appId: '1:992893123986:ios:f005b75f92830e11e7954b',
    messagingSenderId: '992893123986',
    projectId: 'whats-app-713e4',
    storageBucket: 'whats-app-713e4.appspot.com',
    iosClientId: '992893123986-uudjlfl2glvvvfs4oapktc0ne8tbv438.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsApp',
  );
}
